config/routes.rb
Deals8065::Application.routes.draw do
  
  resources :deals

  devise_for :users

  root :to => 'deals#index'
  
  
  get 'free' => "deals#free"
  
  get 'review' =>  'deals#orderReview'

  get 'contact' => "pages#contact"

  get 'advertise' => "pages#advertise"
  
  get 'faqs' => "pages#faqs"

end

app/models/deal.rb
class Deal < ActiveRecord::Base
  attr_accessible :businessContact, :businessHours, :businessLocation, :businessName, :detail1, :detail2, :detail3, :detail4, :detail5, :detail6, :detail7, :longDescription, :name, :price, :saleEnd, :saleStart, :shortDescription, :validEnd, :validStart, :value, :voucherLimit, :image
  
  validates :businessContact, :businessHours, :businessLocation, :businessName, :detail1, :detail2, :detail3, :longDescription, :name, :price, :saleEnd, :saleStart, :shortDescription, :validEnd, :validStart, :value, :voucherLimit, presence: true
  
  validates :shortDescription, :length => { :in => 45..105 }
   
  validates_attachment :image, presence: true,
                               content_type: {content_type:['image/jpeg', 'image/jpg', 'image/png', 'image/gif']},
                               size: { less_than: 5.megabytes}
                               
  has_attached_file :image, styles: { medium: "320x320"}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :admin
  # attr_accessible :title, :body
  
  validates :name, :presence => true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  # GET /deals
  # GET /deals.json
  def index
    @deals = Deal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @deals }
    end
  end
  
  def free
    @deals = Deal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @deals }
    end
  end
  
  # GET /deals/1
  # GET /deals/1.json
  def show
    @deal = Deal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @deal }
    end
  end
  
  def orderReview
    @deal = Deal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @deal }
    end
  end

  # GET /deals/new
  # GET /deals/new.json
  def new
    @deal = Deal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @deal }
    end
  end

  # GET /deals/1/edit
  def edit
    @deal = Deal.find(params[:id])
  end

  # POST /deals
  # POST /deals.json
  def create
    @deal = Deal.new(params[:deal])

    respond_to do |format|
      if @deal.save
        format.html { redirect_to @deal, notice: 'Deal was successfully created.' }
        format.json { render json: @deal, status: :created, location: @deal }
      else
        format.html { render action: "new" }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /deals/1
  # PUT /deals/1.json
  def update
    @deal = Deal.find(params[:id])

    respond_to do |format|
      if @deal.update_attributes(params[:deal])
        format.html { redirect_to @deal, notice: 'Deal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal = Deal.find(params[:id])
    @deal.destroy

    respond_to do |format|
      format.html { redirect_to deals_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def free
  end

  def contact
  end

  def advertise
  end
  
  def faqs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/deals/_deal.html.erb
<div class="container" style="max-width:700px">
		<h1>Today's deals</h1>
	
		<% @deals.each do |deal| %>
			<%if deal.price != 0 %>	
				<div class="box">
					<%= image_tag deal.image.url(:medium) %>
					<%= deal.name %><br>
					<div class="description-box">
						<small>	<%= deal.shortDescription.truncate(105) %> <%= deal.shortDescription.length %> </small>
					</div>
					<%= link_to 'View Deal', deal, :class => "btn btn-primary btn-primary pull-right", :style => "position:relative;" %>
					<h2 class="pull-left" style="position:relative; line-height:15px">₱<%= deal.price %> </h2>				
				</div>
			<% end %>
		<% end %>
</div>

app/views/deals/_form.html.erb
<%= simple_form_for(@deal) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :shortDescription %>
    <%= f.input :longDescription %>
		<%= f.input :image %>
    <%= f.input :detail1 %>
    <%= f.input :detail2 %>
    <%= f.input :detail3 %>
    <%= f.input :detail4 %>
    <%= f.input :detail5 %>
    <%= f.input :detail6 %>
    <%= f.input :detail7 %>
    <%= f.input :saleStart %>
    <%= f.input :saleEnd %>
    <%= f.input :validStart %>
    <%= f.input :validEnd %>
    <%= f.input :price %>
    <%= f.input :value %>
    <%= f.input :businessName %>
    <%= f.input :businessHours %>
    <%= f.input :businessLocation %>
    <%= f.input :businessContact %>
    <%= f.input :voucherLimit %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/deals/_showLower.html.erb
<div class="well container" style="width:600px; height:320px">
	<div class="pull-left" style="width:300px;position:relative;left:30px">
		<h2 class="text-left">Goodies</h2>
			<p><%= @deal.detail1 %></p>
			<p><%= @deal.detail2 %></p>
			<p><%= @deal.detail3 %></p>
			<p><%= @deal.detail4 %></p>
			<p><%= @deal.detail5 %></p>
			<p><%= @deal.detail6 %></p>
			<p><%= @deal.detail7 %></p>
			
			
	</div>
	<div class="pull-left" style="width:300px;">
		<h2 class="text-left">Deal Details</h2>
		<p>
		  <b>Selling Period:</b>
		  <%= @deal.saleStart.time.localtime.strftime("%m-%d-%Y") %> to <%= @deal.saleEnd.time.localtime.strftime("%m-%d-%Y") %>
		</p>

		<p>
		  <b>Validity Period:</b>
		  <%= @deal.validStart.time.localtime.strftime("%m-%d-%Y") %>
			<%= @deal.validEnd.time.localtime.strftime("%m-%d-%Y") %>
		</p>

		<p>
		  <b>Business name:</b>
		  <%= @deal.businessName %>
		</p>

		<p>
		  <b>Business hours:</b>
		  <%= @deal.businessHours %>
		</p>

		<p>
		  <b>Business location:</b>
		  <%= @deal.businessLocation %>
		</p>

		<p>
		  <b>Business contact:</b>
		  <%= @deal.businessContact %>
		</p>

		<p>
		  <b>Voucherlimit:</b>
		  <%= @deal.voucherLimit %>
		</p>
	</div>
		
</div>

app/views/deals/_showUpper.html.erb
	<div class="well show-box1 container">	
		<%= image_tag @deal.image.url(:medium), :class => 'pull-left' %>
		<div class="pull-left inner-show-box1">
	  	<h4><%= @deal.name %></h4>
			
			<h2 class="price pull-left"> 
				<% if @deal.price == 0 %>FREE
				<% else %> 
				₱<%= @deal.price %> 
				<% end %>
			</h2>
			<%= link_to "Get Deal", { :controller => "deals", :action => "orderReview", :id => @deal }, :class => 'btn btn-primary btn-large pull-right' %>
 
		
			<div style="position:relative; top:30px; left:30px">
				<table class="table table-striped">
					<tr>
						<th>Value</th>
						<th>Saving</th>
						<th>Price</th>
					</tr>
					<tr>
						<td><%= @deal.value %></td>
						<td><%= '50 %' %></td>
						<td><%= @deal.price %></td>
					</tr>
				</table>
		</div>
		<div style="position:relative; top:30px; left:30px">
		  <%= @deal.longDescription %>
		</div>
	</div>
</div>

app/views/deals/edit.html.erb
<h1>Editing deal</h1>

<%= render 'form' %>

<%= link_to 'Show', @deal %> |
<%= link_to 'Back', deals_path %>

app/views/deals/free.html.erb
<% @deals.each do |deal| %>	
<% if deal.price == 0 %>
<div class="box">
		<%= image_tag deal.image.url(:medium) %>
		<%= deal.name %><br>
		<div class="description-box">
				<small>	<%= deal.shortDescription.truncate(105) %> <%= deal.shortDescription.length %> </small>
		</div>
		<%= link_to 'View Deal', deal, :class => "btn btn-primary btn-primary pull-right", :style => "position:relative;" %>
		<h2 class="pull-left" style="position:relative; line-height:15px">FREE </h2>		
	
	</div>
<% end %>
<% end %>

app/views/deals/index.html.erb
<% if user_signed_in? %>

	<%= render 'deals/deal' %>


	<!-- <table class="table table-striped">
	  <tr>
	    <th>Name</th>
	    <th>Shortdescription</th> -->
	    <!-- <th>Longdescription</th>
	    <th>Detail1</th>
	    <th>Detail2</th>
	    <th>Detail3</th>
	    <th>Detail4</th>
	    <th>Detail5</th>
	    <th>Detail6</th>
	    <th>Detail7</th>
	    <th>Salestart</th>
	    <th>Saleend</th>
	    <th>Validstart</th>
	    <th>Validend</th> -->
	    <!-- <th>Price</th> -->
	    <!-- <th>Value</th>
	    <th>Businessname</th>
	    <th>Businesshours</th>
	    <th>Businesslocation</th>
	    <th>Businesscontact</th>
	    <th>Voucherlimit</th> -->
	    <!-- <th></th>
	    <th></th>
	    <th></th>
	  </tr> -->

	<!-- <% @deals.each do |deal| %>
	  <tr>
	    <td><%= deal.name %></td>
	    <td><%= deal.shortDescription %></td> -->
	    <!-- <td><%= deal.longDescription %></td>
	    <td><%= deal.detail1 %></td>
	    <td><%= deal.detail2 %></td>
	    <td><%= deal.detail3 %></td>
	    <td><%= deal.detail4 %></td>
	    <td><%= deal.detail5 %></td>
	    <td><%= deal.detail6 %></td>
	    <td><%= deal.detail7 %></td>
	    <td><%= deal.saleStart %></td>
	    <td><%= deal.saleEnd %></td>
	    <td><%= deal.validStart %></td>
	    <td><%= deal.validEnd %></td> -->
	    <!-- <td><%= deal.price %></td> -->
	    <!-- <td><%= deal.value %></td>
	    <td><%= deal.businessName %></td>
	    <td><%= deal.businessHours %></td>
	    <td><%= deal.businessLocation %></td>
	    <td><%= deal.businessContact %></td>
	    <td><%= deal.voucherLimit %></td> -->
	    <!-- <td><%= link_to 'Show', deal, :class => "btn btn-mini btn-primary"
	 %></td>
			<% if current_user.try(:admin?) %>
	    <td><%= link_to 'Edit', edit_deal_path(deal) %></td>
	    <td><%= link_to 'Destroy', deal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			<% end %>
	  </tr>
	<% end %>
	</table> -->

				<div style="clear:both;"></div>

	<% if current_user.try(:admin?) %>
	<%= link_to 'New Deal', new_deal_path %>
	<% end %>
	
<% else %>
	<div class="hero-unit">
	  <h1>Welcome to 8065 Deals!</h1>
	  <p>Be apart of an exclusive group and get the deals you want.</p>
	  <p>
	  	<%= link_to "Sign Up", new_user_registration_path, :class => "btn btn-primary btn-large" %>
	  </p>
	</div>
<% end %>

app/views/deals/new.html.erb
<h1>New deal</h1>

<%= render 'form' %>

<%= link_to 'Back', deals_path %>

app/views/deals/orderReview.html.erb
<div class="well container" style="width:850px;">
	<h3>Your Order</h3>
	<div>
		<table class="table table-striped">		
			<tr>
				<th>Description</th>
				<th>Quantity</th>
				<th>Price</th>
				<th>Total</th>
			</tr>
			<tr>
				<td style="width:250px"><small> <%= @deal.longDescription %></small></td>
				<td>
					<select>
					  <option value="1">1</option>
					  <!-- <option value="2">2</option>
					  <option value="3">3</option>
					  <option value="4">4</option> -->
					</select> 
				</td>
				<td><%= @deal.price %></td>
				<td><%= @deal.price * 1 %></td>
			</tr>
		</table>
		<%= link_to 'Print Deal', '#', :class => 'btn btn-primary btn-large pull-right'%>

	</div>	
	
</div>

app/views/deals/show.html.erb
<%= render 'deals/showUpper'%>
<%= render 'deals/showLower'%>

<!-- <p>
  <b>Shortdescription:</b>
  <%= @deal.shortDescription %>
</p> -->

</div>

<% if current_user.try(:admin?) %>
<%= link_to 'Edit', edit_deal_path(@deal) %> |
<%= link_to 'Destroy', @deal, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
<%= link_to 'Back', deals_path %>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		<%= link_to 'Have a question?', contact_path %>
		<%= link_to 'Contact', contact_path %>
		<%= link_to 'Advertise', advertise_path %>
	</small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar" style="width:850px; margin-left:auto; margin-right:auto;">
  <div class="navbar-inner">
    <%= link_to '8065 Deals', root_path, :class => "brand" %>
    <ul class="nav">
      <li><%= link_to 'Today\'s Deals' , root_path %></li>
      <li><%= link_to 'Free', free_path %></li>
			<li><%= link_to 'Contact', contact_path %></li>
			<li><%= link_to 'Advertise', advertise_path %></li>
    </ul>
    <ul class="nav pull-right">
			<% if current_user.try(:admin?) %>
			<li><%= link_to 'Admin' , '#' %></li>
			<%end%>
			<% if user_signed_in? %>
				<li><%= link_to 'Edit Profile' , edit_user_registration_path %></li>
				<li><%= link_to 'Logout' , destroy_user_session_path, :method => :delete %></li>
			<% else %>
				<li><%= link_to 'Login' , new_user_session_path %></li>
			<% end %>
				
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Deals8065</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">	
		<%= render 'layouts/header' %>
    <% flash.each do |name, msg| %>
    	<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
    <% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/advertise.html.erb
<h1>Pages#advertise</h1>
<p>Find me in app/views/pages/advertise.html.erb</p>
<% if current_user.try(:admin?) %>
<li><%= link_to 'Edit Profile' , edit_user_registration_path %></li>
<%else%>
put this
<% end %>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/free.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>
	<h1>You are signed in!</h1>
<% else %>

	<div class="hero-unit">
	  <h1>Welcome to 8065 Deals!</h1>
	  <p>Be apart of an exclusive group and get the deals you want.</p>
	  <p>
	  	<%= link_to "Sign Up", new_user_registration_path, :class => "btn btn-primary btn-large" %>
	  </p>
	</div>
<% end %>